#!/bin/sh

cd

#curl http://192.168.1.50:8000/deb/build/macsrc.tar.gz > macsrc.tar.gz

rm -r build
mkdir build
cd build
tar -zxvf ../share/wolfcam-build/macsrc.tar.gz
mkdir bin
make
cp build/release-darwin-x86/ioquake3.x86 bin/wolfcamqlmac
cp build/release-darwin-x86/renderer_opengl1_x86.dylib bin/
cp build/release-darwin-x86/renderer_opengl2_x86.dylib bin/
cp build/release-darwin-x86/baseq3/*dylib bin/
cd bin
tar -zcvf bin.tar.gz *
#lilweb-deb
cp bin.tar.gz ~/share/wolfcam-build/

