// wolfcam extra ownerdraws and defines

///////     defines    //////////////
// with WCG_GAME_STATUS
#define W_STATUS_WARMUP 0
#define W_STATUS_PLAYING 1
#define W_STATUS_INTERMISSION 2
#define W_STATUS_DISCONNECTED 3

#define W_WEAPON_NONE 0
#define W_WEAPON_GAUNTLET 1
#define W_WEAPON_MACHINEGUN 2
#define W_WEAPON_SHOTGUN 3
#define W_WEAPON_GRENADE_LAUNCHER 4
#define W_WEAPON_ROCKET_LAUNCHER 5
#define W_WEAPON_LIGHTNING 6
#define W_WEAPON_RAILGUN 7
#define W_WEAPON_PLASMAGUN 8
#define W_WEAPON_BFG 9
#define W_WEAPON_GRAPPLING_HOOK 10
#define W_WEAPON_NAILGUN 11
#define W_WEAPON_PROX_LAUNCHER 12
#define W_WEAPON_CHAINGUN 13
#define W_WEAPON_NUM_WEAPONS 14

// weapon ammo special cases
#define W_AMMO_UNKNOWN -2   // hack for following other players since ammo count isn't available
#define W_AMMO_INFINITE -1  //  gauntlet, grapple, insta...


/////////     ownerdraws     ////////////////
#define WCG_GAME_STATUS 7000

#define WCG_WEAPON_SELECTED 7001
#define WCG_WEAPON_SELECT_TIME 7002
#define WCG_NUMBER_OF_HELD_WEAPONS 7003

// weapon none
#define WCG_WEAPON_HAVE_GAUNTLET 7005
#define WCG_WEAPON_HAVE_MACHINEGUN 7006
#define WCG_WEAPON_HAVE_SHOTGUN 7007
#define WCG_WEAPON_HAVE_GRENADE_LAUNCHER 7008
#define WCG_WEAPON_HAVE_ROCKET_LAUNCHER 7009
#define WCG_WEAPON_HAVE_LIGHTNING 7010
#define WCG_WEAPON_HAVE_RAILGUN 7011
#define WCG_WEAPON_HAVE_PLASMAGUN 7012
#define WCG_WEAPON_HAVE_BFG 7013
#define WCG_WEAPON_HAVE_GRAPPLING_HOOK 7014
#define WCG_WEAPON_HAVE_NAILGUN 7015
#define WCG_WEAPON_HAVE_PROX_LAUNCHER 7016
#define WCG_WEAPON_HAVE_CHAINGUN 7017

// none -- skip
#define WCG_WEAPON_AMMO_GAUTNLET 7019
#define WCG_WEAPON_AMMO_MACHINEGUN 7020
#define WCG_WEAPON_AMMO_SHOTGUN 7021
#define WCG_WEAPON_AMMO_GRENADE_LAUNCHER 7022
#define WCG_WEAPON_AMMO_ROCKET_LAUNCHER 7023
#define WCG_WEAPON_AMMO_LIGHTNING 7024
#define WCG_WEAPON_AMMO_RAILGUN 7025
#define WCG_WEAPON_AMMO_PLASMAGUN 7026
#define WCG_WEAPON_AMMO_BFG 7027
#define WCG_WEAPON_AMMO_GRAPPLING_HOOK 7028
#define WCG_WEAPON_AMMO_NAILGUN 7029
#define WCG_WEAPON_AMMO_PROX_LAUNCHER 7030
#define WCG_WEAPON_AMMO_CHAINGUN 7031

#define WCG_REAL_PLAYER_HEAD 7032  // whatever the player has set, ignores using default red and blue skins for team games

#define WCG_KILL_COUNT 7033
